name: deploy-book

# Only run this when the master branch changes
on: [workflow_dispatch]
  #push:
  #  branches:
  #  - master

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    # Install pip dependencies
    - name: Install dependencies
      run: |
        $CONDA/bin/pip install pip -U
        $CONDA/bin/pip install -r book/requirements.txt

    # Build the book
    - name: Build the book
      run: |
        $CONDA/bin/jupyter-book build .
    
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
